version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    hostname: rabbitmq
    restart: always
    tty: true
    stdin_open: true
    # network_mode: host
    volumes:
        # - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
        - ./plugins/enable_plugins:/etc/rabbitmq/enabled_plugins:ro
        - ./_db:/var/lib/rabbitmq/mnesia
        # More plugins on:
        # https://www.rabbitmq.com/plugins.html
        # https://www.rabbitmq.com/community-plugins.html
    ports:
        # HTTP DASHBOARD FOR MANAGEMENT
        - "15672:15672"
        # AMQP PROTOCOL
        - "5672:5672"
        # MQTT PROTOCOL
        - "1883:1883"
        # MQTT OVER WEBSOCKETS
        - "15675:15675"